[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wordcount"
version = "1.0.0"
readme = "README.md"
dependencies = [
    "pytest",
    "pytest-timeout",
    "rich",
]

[project.scripts]
wordcount = "wordcount:main"

[tool.black]
line-length = 79
