# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="recommendations.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x15recommendations.proto"^\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1f\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\r.BookCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05"/\n\x12\x42ookRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t"F\n\x16RecommendationResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.BookRecommendation*?\n\x0c\x42ookCategory\x12\x0b\n\x07MYSTERY\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\r\n\tSELF_HELP\x10\x02\x32O\n\x0fRecommendations\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponseb\x06proto3',
)

_BOOKCATEGORY = _descriptor.EnumDescriptor(
    name="BookCategory",
    full_name="BookCategory",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="MYSTERY",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="SCIENCE_FICTION",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="SELF_HELP",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=242,
    serialized_end=305,
)
_sym_db.RegisterEnumDescriptor(_BOOKCATEGORY)

BookCategory = enum_type_wrapper.EnumTypeWrapper(_BOOKCATEGORY)
MYSTERY = 0
SCIENCE_FICTION = 1
SELF_HELP = 2


_RECOMMENDATIONREQUEST = _descriptor.Descriptor(
    name="RecommendationRequest",
    full_name="RecommendationRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="user_id",
            full_name="RecommendationRequest.user_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="category",
            full_name="RecommendationRequest.category",
            index=1,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="max_results",
            full_name="RecommendationRequest.max_results",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=25,
    serialized_end=119,
)


_BOOKRECOMMENDATION = _descriptor.Descriptor(
    name="BookRecommendation",
    full_name="BookRecommendation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="BookRecommendation.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="title",
            full_name="BookRecommendation.title",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=121,
    serialized_end=168,
)


_RECOMMENDATIONRESPONSE = _descriptor.Descriptor(
    name="RecommendationResponse",
    full_name="RecommendationResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="recommendations",
            full_name="RecommendationResponse.recommendations",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=170,
    serialized_end=240,
)

_RECOMMENDATIONREQUEST.fields_by_name["category"].enum_type = _BOOKCATEGORY
_RECOMMENDATIONRESPONSE.fields_by_name[
    "recommendations"
].message_type = _BOOKRECOMMENDATION
DESCRIPTOR.message_types_by_name[
    "RecommendationRequest"
] = _RECOMMENDATIONREQUEST
DESCRIPTOR.message_types_by_name["BookRecommendation"] = _BOOKRECOMMENDATION
DESCRIPTOR.message_types_by_name[
    "RecommendationResponse"
] = _RECOMMENDATIONRESPONSE
DESCRIPTOR.enum_types_by_name["BookCategory"] = _BOOKCATEGORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecommendationRequest = _reflection.GeneratedProtocolMessageType(
    "RecommendationRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECOMMENDATIONREQUEST,
        "__module__": "recommendations_pb2"
        # @@protoc_insertion_point(class_scope:RecommendationRequest)
    },
)
_sym_db.RegisterMessage(RecommendationRequest)

BookRecommendation = _reflection.GeneratedProtocolMessageType(
    "BookRecommendation",
    (_message.Message,),
    {
        "DESCRIPTOR": _BOOKRECOMMENDATION,
        "__module__": "recommendations_pb2"
        # @@protoc_insertion_point(class_scope:BookRecommendation)
    },
)
_sym_db.RegisterMessage(BookRecommendation)

RecommendationResponse = _reflection.GeneratedProtocolMessageType(
    "RecommendationResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _RECOMMENDATIONRESPONSE,
        "__module__": "recommendations_pb2"
        # @@protoc_insertion_point(class_scope:RecommendationResponse)
    },
)
_sym_db.RegisterMessage(RecommendationResponse)


_RECOMMENDATIONS = _descriptor.ServiceDescriptor(
    name="Recommendations",
    full_name="Recommendations",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=307,
    serialized_end=386,
    methods=[
        _descriptor.MethodDescriptor(
            name="Recommend",
            full_name="Recommendations.Recommend",
            index=0,
            containing_service=None,
            input_type=_RECOMMENDATIONREQUEST,
            output_type=_RECOMMENDATIONRESPONSE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_RECOMMENDATIONS)

DESCRIPTOR.services_by_name["Recommendations"] = _RECOMMENDATIONS

# @@protoc_insertion_point(module_scope)
