# Generated by Django 6.1 on 2026-09-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("historical_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="volume",
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
