[tool.poetry]
name = "huggingface-transformers"
version = "0.1.0"
description = ""
authors = ["hfhoffman1144 <hfh160130@utdallas.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
accelerate = "^1.15.0"
ipywidgets = "^8.1.9"
notebook = "^7.6.3"
pillow = "^12.3.0"
polars = "^2.0.0"
torch = "^2.14.1"
transformers = "^5.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
