# Generated by Django 4.2.6 on 2023-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dmd_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="markdowncontent",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
